name: py310
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py310h5f69134_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - astunparse=1.6.3=pyhd8ed1ab_3
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.7.11=ha4ce7b8_1
  - aws-c-cal=0.6.9=h4fd42c2_3
  - aws-c-common=0.9.12=h93a5062_0
  - aws-c-compression=0.2.17=h4fd42c2_8
  - aws-c-event-stream=0.4.1=he66824e_2
  - aws-c-http=0.8.0=hd3d28cd_2
  - aws-c-io=0.14.0=h8daa835_1
  - aws-c-mqtt=0.10.1=h59ff425_0
  - aws-c-s3=0.4.9=h7f99a2c_0
  - aws-c-sdkutils=0.1.13=h4fd42c2_1
  - aws-checksums=0.1.17=h4fd42c2_7
  - aws-crt-cpp=0.26.0=hfff802b_8
  - aws-sdk-cpp=1.11.210=he93ac2d_10
  - blas=2.132=openblas
  - blas-devel=3.9.0=32_h11c0a38_openblas
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=h5505292_3
  - brotli-bin=1.1.0=h5505292_3
  - brotli-python=1.1.0=py310h853098b_3
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.2=pyhd8ed1ab_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.2=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cryptography=45.0.5=py310h69cbf43_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.15=py310hf6ed2a0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - flatbuffers=23.5.26=h13dd4ca_1
  - fonttools=4.59.0=py310h5f69134_0
  - freetype=2.13.3=hce30654_1
  - frozenlist=1.7.0=py310ha18c8e3_0
  - gast=0.6.0=pyhd8ed1ab_0
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.6.0=h6da1cb0_0
  - google-auth=2.40.3=pyhd8ed1ab_0
  - google-auth-oauthlib=1.2.2=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_2
  - grpcio=1.59.3=py310hf7687f1_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.14.0=nompi_py310h758c3a9_100
  - hdf5=1.14.6=nompi_ha698983_101
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.8=py310h7f4e7e6_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libaec=1.1.4=h51d1e36_0
  - libarrow=14.0.2=h4ce3932_3_cpu
  - libarrow-acero=14.0.2=h13dd4ca_3_cpu
  - libarrow-dataset=14.0.2=h13dd4ca_3_cpu
  - libarrow-flight=14.0.2=ha94d253_3_cpu
  - libarrow-flight-sql=14.0.2=h39a9b85_3_cpu
  - libarrow-gandiva=14.0.2=hf757142_3_cpu
  - libarrow-substrait=14.0.2=h7fd9903_3_cpu
  - libblas=3.9.0=32_h10e41b3_openblas
  - libbrotlicommon=1.1.0=h5505292_3
  - libbrotlidec=1.1.0=h5505292_3
  - libbrotlienc=1.1.0=h5505292_3
  - libcblas=3.9.0=32_hb3479ef_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=20.1.8=hf598326_1
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libgoogle-cloud=2.12.0=hfb399a7_4
  - libgrpc=1.59.3=h9560976_0
  - libiconv=1.18=hfe07756_1
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=32_hc9a63f6_openblas
  - liblapacke=3.9.0=32_hbb7bcf8_openblas
  - libllvm15=15.0.7=h2621b3d_4
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.30=openmp_hf332438_0
  - libparquet=14.0.2=hf6ce1d5_3_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=4.24.4=h810fc01_0
  - libre2-11=2023.09.01=h741fcf5_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.7.0=h2f21f7c_5
  - libutf8proc=2.8.0=hc098a78_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.12.7=h9a80f22_3
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=hbb9b287_1
  - lz4-c=1.9.4=hb7217d7_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310hc74094e_1
  - matplotlib=3.10.5=py310hb6292c7_0
  - matplotlib-base=3.10.5=py310he861c53_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - multidict=6.6.3=py310hdf261b0_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py310hd45542a_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openblas=0.3.30=openmp_hea878ba_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.1=h81ee809_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - orc=1.9.2=h7c018df_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py310h1cdf563_1
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h61efb56_0
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py310hc74094e_0
  - protobuf=4.24.4=py310hc08086b_0
  - psutil=7.0.0=py310h078409c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=14.0.2=py310h382c99a_3_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.1.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=h6cefb37_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-flatbuffers=25.2.10=pyhbc23db3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyzmq=27.0.1=py310h315defb_0
  - qhull=2020.2=h420ef59_5
  - re2=2023.09.01=h4cba328_1
  - readline=8.2=h1a28f6b_0
  - requests=2.32.4=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - scipy=1.15.3=py310hb81b3df_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=78.1.1=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.1.10=hd04f947_1
  - sqlite=3.50.4=h6e44f1d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310h307809b_0
  - tensorboard-data-server=0.7.0=py310hddb97a1_2
  - tensorflow-estimator=2.15.0=cpu_py310h0d828bf_2
  - termcolor=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.1=py310h078409c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py310h078409c_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310hca03da5_0
  - wrapt=1.14.1=py310h8e9501a_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yarl=1.20.1=py310hc74094e_0
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py310h078409c_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aeon==1.2.0
      - cloudpickle==3.1.1
      - deprecated==1.2.18
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - fsspec==2025.7.0
      - imbalanced-learn==0.13.0
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - keras==3.11.1
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - mat73==0.65
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - namex==0.1.0
      - networkx==3.4.2
      - numba==0.61.2
      - openpyxl==3.1.5
      - optree==0.17.0
      - pluggy==1.6.0
      - pycatch22==0.4.5
      - pydot==4.0.1
      - pyod==2.0.5
      - pytest==8.4.2
      - pywavelets==1.8.0
      - rich==14.1.0
      - ruff==0.14.2
      - ruptures==1.1.9
      - scikit-learn==1.6.1
      - sklearn-compat==0.1.3
      - sparse==0.17.0
      - stumpy==1.13.0
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tomli==2.3.0
      - torch==2.7.1
      - tsfresh==0.21.0
      - tslearn==0.6.4
prefix: /opt/miniconda3/envs/py310
